# =============================================================================
#  backstage-snow-poc — single image, batteries included
#
#  Follows the official Backstage host-build Docker pattern:
#  https://backstage.io/docs/deployment/docker
#
#  Stages:
#    mock-build        – builds the ServiceNow mock Express server
#    backstage-build   – scaffolds + builds Backstage with the SNow plugin
#    debug             – (optional) target to inspect build output
#    runtime           – lean image; shell supervisor starts both processes
# =============================================================================

# ── Stage 1: ServiceNow mock ──────────────────────────────────────────────────
FROM node:20-alpine AS mock-build
WORKDIR /mock
COPY mock/package.json .
RUN npm install --omit=dev
COPY mock/server.js .

# ── Stage 2: Backstage build ──────────────────────────────────────────────────
FROM node:20-bookworm-slim AS backstage-build

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 make g++ git curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /build

# Scaffold a fresh Backstage app (non-interactive)
RUN npx --yes @backstage/create-app@latest \
    --skip-install \
    --path /build/app \
    --name backstage-snow-poc 2>&1 | tail -5

WORKDIR /build/app

# Install all workspace deps (respects yarn.lock generated by create-app)
RUN yarn install --frozen-lockfile 2>&1 | tail -10

# Add the Roadie ServiceNow frontend plugin
RUN yarn --cwd packages/app add \
    @roadiehq/backstage-plugin-servicenow 2>&1 | tail -5

# ── Patch our custom files into the scaffold ──────────────────────────────────
COPY backstage/app-config.yaml          ./app-config.production.yaml
COPY backstage/catalog/                 ./catalog/
COPY backstage/patches/EntityPage.tsx   ./packages/app/src/components/catalog/EntityPage.tsx
COPY backstage/patches/App.tsx          ./packages/app/src/App.tsx

# Official Backstage backend build:
#   - compiles frontend → static assets
#   - bundles backend + frontend into packages/backend/dist/
RUN yarn build:backend --config app-config.production.yaml 2>&1 | tail -30

# Verify the dist was produced and show what entry point was generated
# (Backstage versions differ: index.js vs index.cjs.js)
RUN echo "=== dist contents ===" && ls -la packages/backend/dist/ && \
    echo "=== entry point ===" && \
    ls packages/backend/dist/index* 2>/dev/null || \
    (echo "ERROR: no index file in dist" && exit 1)

# ── Intermediate debug target (build with --target debug to inspect) ──────────
FROM backstage-build AS debug
# Stop here — useful for: docker build --target debug -t bs-debug .
# Then: docker run --rm -it bs-debug bash
CMD ["bash"]

# ── Stage 3: lean runtime ─────────────────────────────────────────────────────
FROM node:20-bookworm-slim AS runtime

LABEL org.opencontainers.image.title="Backstage ServiceNow POC" \
      org.opencontainers.image.description="Backstage + ServiceNow mock, no real SNow needed"

# Native build tools for sqlite3 if it needs recompiling
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3 make g++ libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*

# ── ServiceNow mock ───────────────────────────────────────────────────────────
WORKDIR /mock
COPY --from=mock-build /mock ./

# ── Backstage ─────────────────────────────────────────────────────────────────
WORKDIR /app

# The dist/ directory is fully self-contained in modern Backstage (>=1.24).
# It includes the bundled backend + embedded static frontend.
COPY --from=backstage-build /build/app/packages/backend/dist/     ./packages/backend/dist/

# Config + catalog (not bundled, read at runtime)
COPY --from=backstage-build /build/app/app-config.production.yaml ./app-config.yaml
COPY --from=backstage-build /build/app/catalog/                   ./catalog/

# Package manifests (needed by Backstage's config loader and plugin resolution)
COPY --from=backstage-build /build/app/package.json               ./package.json
COPY --from=backstage-build /build/app/packages/backend/package.json \
                                                                   ./packages/backend/package.json

# Hoisted node_modules from the workspace root
# (only runtime deps — dev deps were never in the scaffold's production install)
COPY --from=backstage-build /build/app/node_modules/              ./node_modules/

# ── Supervisor ────────────────────────────────────────────────────────────────
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 7007 8181
ENV NODE_ENV=production

ENTRYPOINT ["/entrypoint.sh"]
